version: 2

jobs:

  build:

    docker:

      - image: circleci/python:3.7.3
    working_directory: ~/nuciti

    steps:

      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Restoring environment
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
            pip install flake8

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"

      - run:
          name: Linter
          command: |
            . env/bin/activate
            python -m flake8 ./nuciti/

      - run:
          name: Tests
          command: |
            . env/bin/activate
            mkdir test-reports
            python -m pytest ./tests/ --junitxml=test-reports/junit.xml

      - run:
          name: Coverage
          command: |
            . env/bin/activate
            python -m pytest --cov=nuciti ./tests/

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
  version: 2

  dev:
    jobs:
      - build

